[package]
name = "spinoso-regexp"
version = "0.5.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
description = """
Regex implementation for Ruby Regexp core type in Artichoke Ruby
"""
keywords = ["artichoke", "onig", "regex", "regexp", "ruby"]
categories = ["data-structures", "parser-implementations"]
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
bitflags = "2.3.3"
posix-space = "1.0.2"

[dependencies.bstr]
version = "1.2.0"
default-features = false
features = ["alloc"]

[dependencies.onig]
version = "6.4.0"
optional = true
default-features = false

[dependencies.regex]
version = "1.7.0"
default-features = false
features = ["std", "unicode-perl"]

[dependencies.scolapasta-aref]
version = "0.1.0"
path = "../scolapasta-aref"

[dependencies.scolapasta-string-escape]
version = "0.3.0"
path = "../scolapasta-string-escape"
default-features = false

[features]
default = ["oniguruma", "regex-full"]
oniguruma = ["dep:onig"]
regex-full = ["regex-perf", "regex-unicode"]
regex-perf = ["regex/perf"]
regex-unicode = ["regex/unicode"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
