---
"on":
  push:
    branches:
      - trunk
    paths:
      - .github/markdown-link-check.json
      - .github/workflows/markdown-link-check.yaml
      - "**/*.md"
  pull_request:
    branches:
      - trunk
    paths:
      - .github/markdown-link-check.json
      - .github/workflows/markdown-link-check.yaml
      - "**/*.md"
  schedule:
    - cron: "0 0 * * TUE"
name: Markdown Links Check
jobs:
  check-links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Install Ruby toolchain
        uses: ruby/setup-ruby@1d0e911f615a112e322369596f10ee0b95b010ae # v1.183.0
        with:
          ruby-version: ".ruby-version"
          bundler-cache: true

      - name: Check for broken links in markdown files
        run: bundle exec rake release:markdown_link_check
